-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(50) NOT NULL,
    email character varying(50) UNIQUE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    job_seekers_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    identitiy_number character varying(11) UNIQUE NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (job_seekers_id)
);

CREATE TABLE public.employers
(
    employers_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    company_name character varying(50) NOT NULL,
    web_site character varying(50) NOT NULL,
    phone_number character varying(13) NOT NULL,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public.system_personel
(
    system_personels_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    PRIMARY KEY (system_personels_id)
);

CREATE TABLE public.activation_codes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    activation_code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_code_for_job_seekers
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_seekers bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_code_for_employer
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    employers bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    PRIMARY KEY (id)
);

ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (job_seekers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_personel
    ADD FOREIGN KEY (system_personels_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.activation_code_for_employer
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_code_for_job_seekers
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_code_for_job_seekers
    ADD FOREIGN KEY (job_seekers)
    REFERENCES public.job_seekers (job_seekers_id)
    NOT VALID;


ALTER TABLE public.activation_code_for_employer
    ADD FOREIGN KEY (employers)
    REFERENCES public.employers (employers_id)
    NOT VALID;

END;